# Generated by Django 5.1.5 on 2025-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_aluno_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='presenca',
            field=models.CharField(choices=[('vai_volta', 'Vai e volta'), ('so_vai', 'Só vai'), ('so_volta', 'Só volta'), ('nao_vai', 'Não vai e não volta')], default='vai_volta', max_length=20),
        ),
    ]
