# Generated by Django 5.1.5 on 2025-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_aluno_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_presenca',
            field=models.DateField(blank=True, null=True),
        ),
    ]
